### ISSUE TITLE
Navigate to next picture opens some hidden meaningless .JPG files

### ISSUE THREAD

**Issue by ivanyurchenko1** [sprout2000/leafview#22]
Instead of navigating to .JPG files it starts opening `.*imagename*.JPG` files that don't contain anything.

**Comment by sprout2000** [comment]
Thank you for your review, @ivanyurchenko1 

> it starts opening .*imagename*.JPG files

Oh... They should be 'dot_underscore' files coming from macOS file system.  
Not harmful, but very annoying.  
I fixed it on version 0.2.5 coming soon on [Microsoft Store](https://www.microsoft.com/store/apps/9P870THX6217).

Would you please wait a few days and try it?

**Comment by ivanyurchenko1** [comment]
Sure, thanks for a quick response! The issue occured on macos version, I was looking for something instead of macos preview app. Let me know how it goes

Ivan

**Comment by sprout2000** [comment]
@ivanyurchenko1 

> The issue occured on macos version

Hmm.. Would you try [v0.2.7](https://github.com/sprout2000/leafview/releases/tag/v0.2.7) ?  
Best regards.

**Comment by sprout2000** [comment]
There seems to be no further feedback, so I'm closing this issue.
