### ISSUE TITLE
Suggestion: support switch images by keyboard

### ISSUE THREAD

**Issue by rsun-thoughtworks** [sprout2000/leafview#220]
Support switch images by arrow keys on keyboard.

**Comment by sprout2000** [comment]
@rsun-thoughtworks 
Thank you for your suggestion.

This application uses [leaflet.js](https://leafletjs.com/) to achieve pan and zoom.
The arrow keys on the keyboard are assigned to the pan function derived from leaflet, and cannot be changed.
Unfortunately, we will have to continue to use the vi-like J and K keys for image transitions.
