### ISSUE TITLE
2.7.5 - GUI improvements

### ISSUE THREAD

**Issue by bovirus** [sprout2000/leafview#332]
@sprout2000 

Please check screenshots.

- About window

![image](https://github.com/sprout2000/leafview/assets/1262554/b26b1f4b-9c8a-41ad-a5d5-114fc4c34b74)

"and other contributors" in trademark for me could be remove.
Also in the instalelr could remove it
For me the copyright could be "(c) 2020-2023 sprout2000"

"LeafView" on top left could be renamed as "About LeafView" and add to the language file ("Info su LeafView" in Italian)

In version field "(27.0.4)" could be removed to avoid misunderstanding about version numbering.
Version is 27.0.5

- Installer Exe file properties

![image](https://github.com/sprout2000/leafview/assets/1262554/450590c6-16ce-49f3-93d6-dbfc7344e5bb)

For me the copyright could be "(c) 2020-2023 sprout2000"

**Comment by sprout2000** [comment]
@bovirus 
Thank you for the report with screen shots.
Fixes will be included in the next release.

**Comment by bovirus** [comment]
@sprout2000 

You released 10 hours ago a new release (2.7.7).
But without the fix reported here.

May I check also the Inno Setup installer script (.,iss file) for possible impovements?
Thanks.

**Comment by sprout2000** [comment]
@bovirus 
Since you seem to be using the Windows version, I tried [v2.7.7](https://github.com/sprout2000/leafview/releases/tag/v2.7.7) myself. And the fixes appear to be properly applied.

![スクリーンショット 2023-11-12 083122](https://github.com/sprout2000/leafview/assets/52094761/9bfea0e8-dff4-4ebe-9f32-c0c501566b8c)
![スクリーンショット 2023-11-12 083345](https://github.com/sprout2000/leafview/assets/52094761/e44eea05-0ea3-4564-9e19-63c7dff58106)

Could you please upload your screenshots?

**Comment by sprout2000** [comment]
@bovirus 
Oh... You mean I could remove "and othe contributors". Sorry.
Uh, do you think that's reasonable?

**Comment by bovirus** [comment]
@sprout2000 

The copyright message generally contains info about copyright year (start/end) and company orauthor.

You can add below copyright message a line like "Thanks to all contributors for your important contribution" (add it to the language file to enable relative translation"
But is not relative to copyright.
Same think about copyright info in the installer (just startcopyright year-Endcopyrightyerar company or author).

About  Eecroun version use a strings like

v. 2.7.7 (Electron v. 27.0.4)

Please take care about space after "v." and adding of "Electon".
More clear.

Then you can change the string in about window like

LeafView v. 2.7.7 (Electron v. 27.0.4)

(c) 2020-2023 sprout2000

Thanks to all contributors for your important contribution

In "About" window change "LeafView" with "About LeafView" and add "About" is not already included in language file.

**Comment by sprout2000** [comment]
@bovirus 
OK. I undarstand.
Although there are limitations due to the Electron API specification, I will try to do the best I can.

**Comment by sprout2000** [comment]
See [electron/electron](https://github.com/electron/electron/releases/tag/v27.1.0).

<img width="327" alt="スクリーンショット 2023-11-16 115312" src="https://github.com/sprout2000/leafview/assets/52094761/a550a01d-2d3d-4e15-94b3-2f1fe1957416">

**Comment by bovirus** [comment]
@sprout2000 

Thanks for changes.

My proposal

![image](https://github.com/sprout2000/leafview/assets/1262554/7aafb2fa-df5f-43b3-a529-b404f7aa91d5)

Please take care about new lines in About window between text strings and Caption text on top left

**Comment by sprout2000** [comment]
@bovirus 
Thank you for your suggestions.
Unfortunately, there is no way to change that part due to limitations imposed by the Electron API: [app.setAboutPanelOptions(options)](https://www.electronjs.org/docs/latest/api/app#appsetaboutpaneloptionsoptions).

**Comment by bovirus** [comment]
@sprout2000 

Also for Caption on top left?

**Comment by sprout2000** [comment]
@bovirus 
Unfortunately, that is also out of the developer's control.
