### ISSUE TITLE
Windows 10 (Microsoft Store) not available

### ISSUE THREAD

**Issue by thomasthebear** [sprout2000/leafview#62]
Not entirely sure if you've realized, or were aware that the link you have available for downloading the compiled version through the Microsoft Store leads nowhere, unfortunately. Not sure if Microsoft removed the software or what the case may be, but figured you'd want to know if you didn't already. 

Edit: Seems like, on occasions, the link will give an error when you try to view the software, where other times it will give show the software. Odd little issue, more then likely on Microsoft's side. Kept playing with it, and noticed the issue wasn't you all's problem. Apologies.

**Comment by sprout2000** [comment]
Due to limited personal development resources, I will only release new versions via [Winget](https://learn.microsoft.com/en-us/windows/package-manager/winget/) in the future.
