### ISSUE TITLE
GNU/Linux

### ISSUE THREAD

**Issue by yutyo** [sprout2000/leafview#70]
Do you think a GNU/Linux support?

**Comment by sprout2000** [comment]
> Do you think a GNU/Linux support?

I'm sorry but I don't have any plan to support Linux.

**Comment by joshskidmore** [comment]
I apologize for commenting on this closed issue. I use Arch linux and was able to clone the repo, and use `yarn start` as well as `yarn package` without any code modifications. The `yarn package` phase generates an AppImage, snap file as well as an unpackaged directory with the built application.

I have not used LeafView on MacOS or Windows, but all the noted features seem to work beautifully. I'm able to open an image (or folder of images) using `./LeafView-0.6.3.AppImage [IMG/FOLDER]` as well as using the `Alt` keybinding, and opening from a menu. All the keybindings work well as well. 

Here are the untouched binaries generated from `yarn package` if you're interested:

- [LeafView-0.6.3.AppImage](https://josh.sh/LeafView-0.6.3.AppImage) (sha256sum: `165338916f51749d59e0c03aec0730fc460bb3ef599c111ef40f150f32e1e9dd`)
- [leafview_0.6.3_amd64.snap](https://josh.sh/leafview_0.6.3_amd64.snap) (sha256sum: `d07a76c79d7236e66c344979b6b79233749e7fc0cbe12e9d95496494e91dbfde`)
- [leafview-0.6.3-linux-unpacked.tar.gz](https://josh.sh/leafview-0.6.3-linux-unpacked.tar.gz) (sha256sum: `a19912f14edc1c590babb6a84a2eb6e7a7e9e09832e6bf7b5a552069ca507e8c`)

**Comment by sprout2000** [comment]
@joshskidmore 
Thank you so much for the information.

> Attempting to open an image of folder of images using a command line parameter doesn't seem to work in linux. This might not even be a feature on the other platforms either.

I also checked it on Ubuntu.
Not intended to be used from the command line on macOS or Windows.

>  I am, however, also able to click the folder icon and open in a similar fashion as using the menu > open method.

It is good news, though I don't know how to give an icon to this app on Linux ...
Anyway, thank you very much.

![Screenshot from 2021-01-19 14-28-39](https://user-images.githubusercontent.com/52094761/104993789-b7198880-5a66-11eb-8957-bfe305480598.png)

**Comment by joshskidmore** [comment]
In all honesty, I've never packaged a desktop app for Ubuntu. Typically GUI application metadata is defined in [APP_NAME].desktop files. The AppImage package (created from `yarn package`) is:

```conf
[Desktop Entry]
Name=LeafView
Exec=AppRun --no-sandbox %U
Terminal=false
Type=Application
Icon=leafview
StartupWMClass=LeafView
X-AppImage-Version=0.6.3
Comment=Secure image viewer for minimalists based on leaflet.js
Categories=Utility;
```

Typically, the icons are placed in `/usr/share/icons/hicolor/[ICON_DIMENSIONS]/apps/leafview.png`. `[ICON_DIMENSIONS]` being `512x512`, `128x128`, etc.

**Comment by sprout2000** [comment]
Please let me know if you figure out how to set the icon.

**Comment by sprout2000** [comment]
@yutyo 
@joshskidmore 

I have added Linux support, albeit on an experimental basis.
Try it out if you like.

![Screenshot from 2021-06-21 16-43-58](https://user-images.githubusercontent.com/52094761/122726434-f3207600-d2b0-11eb-813d-cd9dd8a40cb4.png)

**Note:** _You will need to have node@14.17+ and npm@7.15+ installed._

see [UBUNTU.md](https://github.com/sprout2000/leafview/blob/main/UBUNTU.md)

**Comment by sprout2000** [comment]
AppImage for GNU/Linux is now available from the [release](https://github.com/sprout2000/leafview/releases) page.

**Comment by sprout2000** [comment]
![Screenshot from 2022-09-13 09-41-18](https://user-images.githubusercontent.com/52094761/189783003-b0c48813-7505-4c5e-8575-e9dbfb8ec125.png)

**Comment by sprout2000** [comment]
![Screenshot from 2022-09-13 09-44-51](https://user-images.githubusercontent.com/52094761/189783151-bd04d074-1ce4-4f38-9a4c-c01b28683cd4.png)
